# Yaml code for creating a deployment and service of episode 1 backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend4-deployment
  labels:
    app: backend4

spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend4
  
  template:
    metadata:
      labels:
        app: backend4
    spec:
      # this is the specification of pods
      containers:
        - name: containerback4
          image: muqeem/backend4:latest
          ports:
           - containerPort: 8000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-service/episode4"
            - name: PORT
              value: "8000"

---
# Yaml for making the external service for backend1 deployment

apiVersion: v1
kind: Service
metadata:
  name: backend4-service

spec:
  type: NodePort
  selector:
    app: backend4

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32040
