# Yaml code for creating a deployment and service of episode 1 frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend3-deployment
  labels:
    app: frontend3

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend3
  
  template:
    metadata:
      labels:
        app: frontend3
    spec:
      # this is the specification of pods
      containers:
        - name: containerfront3
          image: muqeem/frontend3:latest
          ports:
           - containerPort: 3000
          env:
            - name: REACT_APP_BASEURL
              value: "http://ip172-18-0-18-cp3icf28dsgg009aei0g.direct.labs.play-with-k8s.com:32030"

---
# Yaml for making the external service for frontend1 deployment

apiVersion: v1
kind: Service
metadata:
  name: frontend3-service

spec:
  type: NodePort
  selector:
    app: frontend3

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32031
