# Yaml code for creating a deployment and service of episode 1 backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend6-deployment
  labels:
    app: backend6

spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend6
  
  template:
    metadata:
      labels:
        app: backend6
    spec:
      # this is the specification of pods
      containers:
        - name: containerback6
          image: muqeem/backend6:latest
          ports:
           - containerPort: 8000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-service/episode6"
            - name: PORT
              value: "8000"

---
# Yaml for making the external service for backend1 deployment

apiVersion: v1
kind: Service
metadata:
  name: backend6-service

spec:
  type: NodePort
  selector:
    app: backend6

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32060
