# Yaml code for creating a deployment and service of episode 1 frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend6-deployment
  labels:
    app: frontend6

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend6
  
  template:
    metadata:
      labels:
        app: frontend6
    spec:
      # this is the specification of pods
      containers:
        - name: containerfront6
          image: muqeem/frontend6:latest
          ports:
           - containerPort: 3000
          env:
            - name: REACT_APP_BASEURL
              value: "http://ip172-18-0-64-cp3pchl1ftig0082ldug.direct.labs.play-with-k8s.com:32060"

---
# Yaml for making the external service for frontend1 deployment

apiVersion: v1
kind: Service
metadata:
  name: frontend6-service

spec:
  type: NodePort
  selector:
    app: frontend6

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32061
